### ISSUE TITLE
Multiple console prints : Cannot set classList in IE 10 & 11 while dragging connections

### ISSUE THREAD

**Issue by pavish** [jsplumb/jsplumb#755]
IE 10 & 11 do not support classList property for SVG elements. While dragging connections, the following stack trace is printed.

```
"TypeError: Unable to get property 'length' of undefined or null reference
   at _setClassName (http://192.168.0.102:9000/static/thirdparty/jsplumb.js:6800:24)
   at _classManip (http://192.168.0.102:9000/static/thirdparty/jsplumb.js:6843:13)
   at Anonymous function (http://192.168.0.102:9000/static/thirdparty/jsplumb.js:6925:17)
   at jsPlumb.each (http://192.168.0.102:9000/static/thirdparty/jsplumb.js:6499:13)
   at addClass (http://192.168.0.102:9000/static/thirdparty/jsplumb.js:6924:13)
   at setHover (http://192.168.0.102:9000/static/thirdparty/jsplumb.js:3608:25)
   at Anonymous function (http://192.168.0.102:9000/static/thirdparty/jsplumb.js:2822:17)
   at Anonymous function (http://192.168.0.102:9000/static/thirdparty/jsplumb.js:2819:25)
   at Anonymous function (http://192.168.0.102:9000/static/thirdparty/jsplumb.js:2819:25)
   at Anonymous function (http://192.168.0.102:9000/static/thirdparty/jsplumb.js:7577:21)"

```
Can be fixed with a simple polyfill by setting classList property for Element.prototype from HTMLElement.prototype. Just wanted to raise the issue single multiple console prints slow down the performance.

**Comment by koosvanderkolk** [comment]
Thanks! I used https://polyfill.io to fix this.

`<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>`

**Comment by sporritt** [comment]
what version of jsplumb are you using?

**Comment by koosvanderkolk** [comment]
Ah now I see, I upgraded to 2.8.0 but apparently the cache was not entirely cleared. With 2.8.0 it works fine in IE.
